---
title: "ERoman_Discussion6.rmd"
author: "Enid Roman"
date: "2023-03-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Chapter 3 page 114 

5. Use the program BinomialProbabilities to find the probability that, in 100 tosses of a fair coin, the number of heads that turns up lies between 35 and 65, between 40 and 60, and between 45 and 55.

```{r}
# Testing the outcome of heads or tails
outcomes <- c("heads", "tails")
sample(outcomes, size = 1, replace = TRUE)
```
```{r}
# Testing outcome of heads or tails at 100 tosses
sim_fair_coin <- sample(outcomes, size = 100, replace = TRUE)
sim_fair_coin
```
```{r}
# Total outcome of heads or tails at 100 tosses
table(sim_fair_coin)
```

```{r}
# 100 tosses of a fair coin, the number of heads that turns up lies between 35 and 65
pbinom(35, size = 100, prob = 0.5) - pbinom(65, size = 100, prob = 0.5)
```
```{r}
# 100 tosses of a fair coin, the number of heads that turns up lies between 40 and 60
pbinom(40, size = 100, prob = 0.5) - pbinom(60, size = 100, prob = 0.5)
```
```{r}
# 100 tosses of a fair coin, the number of heads that turns up lies between 45 and 55
pbinom(45, size = 100, prob = 0.5) - pbinom(55, size = 100, prob = 0.5)
```
Reference: https://rc2e.com/index.html#the-recipes
